server:
  port: 8080
spring:
  thymeleaf:
    #清楚页面缓存
    cache: false

dubbo:
  consumer:
    #解除第一次启动不检查消费者存不存在
    check: false
  application:
    name: web-back
  registry:
    address: zookeeper://192.168.154.128:2181
  protocol:
    port: -1

fdfs:
  pool:
    jmx-enabled: false
  thumb-image:
    width: 100
    height: 100
  tracker-list:
    - 192.168.154.128:22122
