dubbo:
  application:
    name: shop-search
  consumer:
    check: false
  registry:
    address: zookeeper://192.168.154.128:2181
  protocol:
    port: -1
spring:
  data:
    solr:
      host: http://192.168.154.128:8983/solr/mycollection
  rabbitmq:
    host: 192.168.154.128
    port: 5672
    username: admin
    password: admin
    virtual-host: /admin
